# Project
version=1.1.0
group=sircow.sunshinegrace
java_version=25

# Common
minecraft_version=26.3
mod_name=Sunshine Grace
mod_author=Sir_Cow, Perpillow
mod_id=sunshinegrace
license=LGPL-3.0-only
credits=
description=Adds a \"grace period\" for players who are joining an existing world for the first time.
minecraft_version_range=[26.3, 26.4)
neo_form_version=26.3-1

# Fabric
fabric_version=0.161.0+26.3
fabric_loader_version=0.19.5
modmenu_version=21.0.0

# Forge
forge_version=66.0.6
forge_loader_version_range=[66,)

# NeoForge
neoforge_version=26.3.0.26-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.configuration-cache=false
